site_name: "EasyFLowQ"
repo_url: https://github.com/ym3141/EasyFlowQ

theme:
  name: readthedocs

nav: 
  - Home: "README.md"
  - Basics: 
    - "Basic usage.md"
    - "Statistics.md"
    - "Batch renaming.md"
    - "Subpopulation.md"
  - Tutorials:
    - "Step-by-step example": "Tutorial.md"
  - About:
    - "Development notes": "Dev notes.md"
    - LICENSE(MIT): "LICENSE.md"

markdown_extensions:
  - attr_list

extra_css:
  - css/extra.css